name: Tests Coverage

on: push

jobs:
  bump:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run tests coverage
      run: npm test:cov
      with:
        branches: main,dev
